#!/usr/bin/env node
/*
 * Vendors mermaid's minified UMD bundle into src/mermaid-lib.js as a base64
 * string constant, so the single-file HTML report (src/render-html.js) can
 * inline the whole renderer with zero runtime dependency and zero CDN call —
 * matching the report's "no server, no CDN, everything inlined" design.
 *
 * Re-run after bumping the `mermaid` devDependency:
 *   npm run vendor:mermaid
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const src = path.join(root, 'node_modules', 'mermaid', 'dist', 'mermaid.min.js');
const out = path.join(root, 'src', 'mermaid-lib.js');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'node_modules', 'mermaid', 'package.json'), 'utf-8'));

if (!fs.existsSync(src)) {
  console.error(`mermaid dist bundle not found at ${src} — run "npm install" first.`);
  process.exit(1);
}

const raw = fs.readFileSync(src, 'utf-8');
const b64 = Buffer.from(raw, 'utf-8').toString('base64');

const banner = `// GENERATED by scripts/vendor-mermaid.mjs — do not edit by hand.
// Vendored mermaid.min.js v${pkg.version}, base64-encoded so it can be inlined
// into a <script> tag without any escaping concerns (backticks, quotes, or a
// literal script-close sequence in the minified source).
// Regenerate with: npm run vendor:mermaid
export const MERMAID_MIN_JS_B64 = "${b64}";
`;

fs.writeFileSync(out, banner, 'utf-8');
console.log(`wrote ${path.relative(root, out)} (mermaid v${pkg.version}, ${Math.round(raw.length / 1024)} KB raw -> ${Math.round(b64.length / 1024)} KB base64)`);
